# Generated by Django 5.2.5 on 2025-08-07 09:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('polygon_coordinates', models.JSONField()),
                ('base_delivery_fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('per_km_rate', models.DecimalField(decimal_places=2, default=0.5, max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('peak_hours_start', models.TimeField(blank=True, null=True)),
                ('peak_hours_end', models.TimeField(blank=True, null=True)),
                ('peak_hours_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Assignée'), ('accepted', 'Acceptée'), ('picked_up', 'Récupérée'), ('in_transit', 'En transit'), ('delivered', 'Livrée'), ('failed', 'Échec'), ('cancelled', 'Annulée')], default='assigned', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_pickup_time', models.DateTimeField()),
                ('estimated_delivery_time', models.DateTimeField()),
                ('actual_pickup_time', models.DateTimeField(blank=True, null=True)),
                ('actual_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('travel_time_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('delivery_fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tip_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('pickup_notes', models.TextField(blank=True)),
                ('delivery_notes', models.TextField(blank=True)),
                ('issue_reported', models.TextField(blank=True)),
                ('delivery_photo', models.ImageField(blank=True, null=True, upload_to='delivery_proofs/')),
                ('customer_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='client.order')),
            ],
            options={
                'verbose_name_plural': 'Deliveries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('address_not_found', 'Adresse introuvable'), ('customer_unavailable', 'Client indisponible'), ('wrong_order', 'Commande incorrecte'), ('damaged_food', 'Nourriture endommagée'), ('payment_issue', 'Problème de paiement'), ('vehicle_breakdown', 'Panne de véhicule'), ('weather_condition', 'Conditions météorologiques'), ('other', 'Autre')], max_length=30)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('reported', 'Signalé'), ('investigating', "En cours d'investigation"), ('resolved', 'Résolu'), ('escalated', 'Escaladé')], default='reported', max_length=20)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('photo_evidence', models.ImageField(blank=True, null=True, upload_to='issue_photos/')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='livreur.delivery')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryPersonProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(blank=True, max_length=50)),
                ('vehicle_type', models.CharField(choices=[('bike', 'Vélo'), ('scooter', 'Scooter'), ('motorcycle', 'Moto'), ('car', 'Voiture'), ('foot', 'À pied')], max_length=20)),
                ('vehicle_registration', models.CharField(blank=True, max_length=50)),
                ('identity_document', models.ImageField(blank=True, null=True, upload_to='delivery_docs/')),
                ('driving_license', models.ImageField(blank=True, null=True, upload_to='delivery_docs/')),
                ('vehicle_insurance', models.ImageField(blank=True, null=True, upload_to='delivery_docs/')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('busy', 'Occupé'), ('offline', 'Hors ligne'), ('on_break', 'En pause')], default='offline', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
                ('delivery_radius', models.PositiveIntegerField(default=10)),
                ('total_deliveries', models.PositiveIntegerField(default=0)),
                ('successful_deliveries', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('max_orders_per_hour', models.PositiveIntegerField(default=4)),
                ('preferred_working_hours_start', models.TimeField(blank=True, null=True)),
                ('preferred_working_hours_end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='livreur.deliverypersonprofile'),
        ),
        migrations.CreateModel(
            name='DeliveryRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('punctuality', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('professionalism', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('food_condition', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('tip_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='livreur.delivery')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('speed', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('heading', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_points', to='livreur.delivery')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_deliveries', models.PositiveIntegerField()),
                ('total_earnings', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_tips', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('paid', 'Payé'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('transaction_reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='livreur.deliverypersonprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('delivery_person', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='DeliveryPersonSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', 'Lundi'), ('tuesday', 'Mardi'), ('wednesday', 'Mercredi'), ('thursday', 'Jeudi'), ('friday', 'Vendredi'), ('saturday', 'Samedi'), ('sunday', 'Dimanche')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('delivery_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='livreur.deliverypersonprofile')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('delivery_person', 'day_of_week')},
            },
        ),
    ]
